# Generated by Django 5.2.3 on 2025-07-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet", "0002_tweet_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
