# Generated by Django 5.2.3 on 2025-07-02 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet", "0003_alter_tweet_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
